services:
  backend:
    container_name: sc-api
    platform: linux/arm64
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5001:5001"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/app
      - /app/SmartCasa.API/bin
      - /app/SmartCasa.API/obj
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5005/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    networks:
      - smart_casa_network

  frontend:
    container_name: sc-ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./ui:/app
      - /app/node_modules
    environment:
      - VITE_DEV_SERVER=true
    networks:
      - smart_casa_network

  db:
    image: postgres:latest
    container_name: sc-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smart_casa
    ports:
      - "5435:5432"
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - smart_casa_network

volumes:
  database:


networks:
  smart_casa_network:
    driver: bridge
